language:
  python

sudo:
  false

virtualenv:
  system_site_packages:
    false
  
env:
  matrix:
    # Python 2
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="false"

    # Python 3
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
      
install:
  source distributions/ci/install.sh

script:
  source distributions/ci/run_tests.sh

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then codecov; fi
