language:
  python

sudo:
  false

virtualenv:
  system_site_packages:
    false
  
env:
  matrix:
    - COVERAGE="false"
    - COVERAGE="true"
      
install:
  source distributions/ci/install.sh

script:
  source distributions/ci/run_tests.sh

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then codecov; fi
